/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Sanjana
 */
public class Home extends javax.swing.JFrame {

    private final JLabel[] binaryLabels = new JLabel[8];

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

        loadBinaryLabels();

    }

    private void loadBinaryLabels() {
        for (int i = 0; i < 8; i++) {
            binaryLabels[i] = new JLabel("0", SwingConstants.CENTER);
            binaryLabels[i].setOpaque(true);
            binaryLabels[i].setBackground(Color.LIGHT_GRAY);
            binaryLabels[i].setFont(new Font("Arial", Font.BOLD, 16));
            display.add(binaryLabels[i]);
        }
    }

     private void showError(String message) {
        JOptionPane.showMessageDialog(this,
                message,
                "Execution Error",
                JOptionPane.ERROR_MESSAGE);
    }

    private void updateBinaryDisplay(String binary) {
        String s = String.format("%8s", binary).replace(' ', '0');
        for (int i = 0; i < 8; i++) {
            char c = s.charAt(i);
            binaryLabels[i].setText(String.valueOf(c));
            binaryLabels[i].setBackground(c == '1' ? Color.GREEN : Color.RED);
        }
    }

    private void convert() {
        String input = inputField.getText().trim();// remove whitespaces - start and end of the text
        String format = String.valueOf(formatSelector.getSelectedItem());
        if (format.equalsIgnoreCase("binary")) {
            if (!input.matches("[1,0]{1,8}")) {
                showError("Enter a valid binary value (up to 8 bits)");
                return;
            }
            String binary = String.format("%8s", input).replace(' ', '0');
            int decimal;
            if (signedRadio.isSelected()) {
                char c = binary.charAt(0);
                decimal = c == '1' ? Integer.parseInt(binary, 2) - 256 : Integer.parseInt(binary, 2);
                resultLabel.setText("Signed Decimal: " + decimal);
            } else { // unsigned radio selected
                decimal = Integer.parseInt(binary, 2);
                resultLabel.setText("Unsigned Decimal: " + decimal);
            }
            updateBinaryDisplay(binary);
        } else if (format.equalsIgnoreCase("decimal")) {
            if (!input.matches("-?\\d+")) {
                showError("Enter a valid decimal number");
                return;
            }
            try {
                int number = Integer.parseInt(input);
                String binary;
                if (signedRadio.isSelected()) {
                    if (number < -128 || number > 127) {
                        throw new NumberFormatException();
                    }
                    binary = String.format("%8s", Integer.toBinaryString(number & 0xFF)).replace(' ', '0');
                    resultLabel.setText("Signed Binary: " + binary);
                } else { //if unsigned radio selected
                    if (number < 0 || number > 255) {
                        throw new NumberFormatException();
                    }
                    binary = String.format("%8s", Integer.toBinaryString(number)).replace(' ', '0');
                    resultLabel.setText("Unsigned Binary: " + binary);
                }
                updateBinaryDisplay(binary);
            } catch (NumberFormatException e) {
                showError("Enter a valid decimal number");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        formatSelector = new javax.swing.JComboBox<>();
        inputField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        unsignRadio = new javax.swing.JRadioButton();
        signedRadio = new javax.swing.JRadioButton();
        display = new javax.swing.JPanel();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Binary Numbering Calculation");
        jLabel1.setPreferredSize(new java.awt.Dimension(379, 40));
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enter Decimal or binary Value :-");

        formatSelector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        formatSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Binary", "Decimal" }));
        formatSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatSelectorActionPerformed(evt);
            }
        });

        inputField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(unsignRadio);
        unsignRadio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unsignRadio.setText("Unsigned (0-255)");

        buttonGroup1.add(signedRadio);
        signedRadio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signedRadio.setText("Signed (-128 To 127)");

        display.setBackground(new java.awt.Color(255, 255, 255));
        display.setLayout(new java.awt.GridLayout(1, 8, 5, 5));

        resultLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(51, 51, 51));
        resultLabel.setText("Result Lable");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(display, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(formatSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(unsignRadio)
                                .addGap(20, 20, 20)
                                .addComponent(signedRadio)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formatSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unsignRadio)
                    .addComponent(signedRadio))
                .addGap(20, 20, 20)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(resultLabel)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formatSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatSelectorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        convert();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel display;
    private javax.swing.JComboBox<String> formatSelector;
    private javax.swing.JTextField inputField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JRadioButton signedRadio;
    private javax.swing.JRadioButton unsignRadio;
    // End of variables declaration//GEN-END:variables
}
